version: '3.8'  # Use the version of Docker Compose that suits your needs

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volume/db:/var/lib/postgresql/data