# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Each job will run on a Runner Machine the type of the runner machine is mentioned below
# All the jobs are run in parallel by default if no condition is specified  Ex: need: build will make the job dependent on build
# Steps - A job can have multiple steps that can be executed one by one Serially
# Action - This will act like a standlone command which are ran Serially
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the code return in the repo -> this step is already written by the Github team we will just use the same here
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: remote-crawler
        environment_name: remote-crawler-Environment
        version_label: 1
        region: us-west-2
        deployment_package: deploy.zip
